// All real images from storytellinginnovation.com, served locally from /images/

export const IMAGES = {
  userLogo: "/images/userLogo.png",
  heroProfessional: "/images/heroProfessional.webp",
  logoNew: "/images/logoNew.webp",
  heroWorkshop: "/images/heroWorkshop.webp",
  pinataMoonBanner: "/images/pinataMoonBanner.webp",
  studentsWriting: "/images/studentsWriting.webp",
  tinythingsCard: "/images/tinythingsCard.webp",
  pinataMoon3d: "/images/pinataMoon3d.webp",
  storygrowCards: "/images/storygrowCards.webp",
  communityActionDeck: "/images/communityActionDeck.webp",
  workshopKautz: "/images/workshopKautz.webp",
  germinationGamesLogo: "/images/germinationGamesLogo.webp",
  songcomingCover: "/images/songcoming-cover.png",
  pinataMoonCover: "/images/pinata-moon-cover.png",
  norwegianStudents: "/images/norwegianStudents.webp",
  upwardBoundWorkshop: "/images/upwardBoundWorkshop.webp",
  csiLogo: "/images/csiLogo.webp",
  teachersWorkshopCooper: "/images/teachersWorkshopCooper.webp",
  groupOutdoor: "/images/groupOutdoor.webp",
  interviewLegacy: "/images/interviewLegacy.webp",
  pinataEvent: "/images/pinataEvent.webp",
  earthDayCarolCover: "/images/earthDayCarolCover.webp",
  upwardBoundCovid: "/images/upwardBoundCovid.webp",
  torranClassroomSelfie: "/images/torranClassroomSelfie.webp",
  writingHand: "/images/writingHand.webp",
  torranTeachingCsi: "/images/torranTeachingCsi.webp",
  torranNorwayClassSelfie: "/images/torranNorwayClassSelfie.webp",
  torranHeadshot: "/images/torranClassroomSelfie.webp",

  // Card images from original site
  booksCard: "/images/books-card.png",
  gamesCard: "/images/games-card.png",
  workshopsCard: "/images/workshops-card.png",
  siteLogo: "/images/site-logo.png",
};
